
#Values corresponding to the defines used
int8 UNDEFINED = 0
int8 OFF = 1
int8 STOPPED = 2
int8 STARTING = 3
int8 IDLE = 4
int8 SUSPENDED = 5
int8 EXECUTE = 6
int8 STOPPING = 7
int8 ABORTING = 8
int8 ABORTED = 9
int8 HOLDING = 10
int8 HELD = 11
int8 RESETTING = 100
int8 SUSPENDING = 101   
int8 UNSUSPENDING = 102
int8 CLEARING = 103
int8 UNHOLDING = 104
int8 COMPLETING = 105
int8 COMPLETE = 106

int8 state
